# Generated by Django 3.0.4 on 2020-03-25 21:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Just another post', max_length=200)),
                ('description', models.TextField(help_text='Describe your need.', max_length=200)),
                ('status', models.CharField(choices=[('AC', 'ACCEPTED'), ('PE', 'PENDING'), ('DE', 'DECLINED')], default='PE', max_length=2)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Just another skill', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('has_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.CharField(default='No comment', max_length=140)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='posts.UserProfile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker', to='posts.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='req_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Skill'),
        ),
        migrations.AddField(
            model_name='post',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.UserProfile'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'ACCEPTED'), ('PE', 'PENDING'), ('DE', 'DECLINED')], default='PE', max_length=2)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.UserProfile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
