# Generated by Django 3.0.4 on 2020-03-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200327_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='has_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Skill'),
        ),
    ]
