# Generated by Django 3.0.4 on 2020-04-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200413_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='average_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
